import type { SiteStyleDefinition } from "./types";

export const THEMES: SiteStyleDefinition[] = [
  {
    styleKey: "editorial_noir",
    name: "Editorial Noir",
    category: "Music",
    description: "High-status music magazine. Dark, refined, typographically driven.",
    sortOrder: 0,
    tokens: {
      colorBackground: "#0E0C09",
      colorBackgroundAlt: "#1A1714",
      colorSurface: "#231F1B",
      colorBorder: "#3A3530",
      colorAccent: "#C9A84C",
      colorAccentHover: "#E0C069",
      colorText: "#F0E8D8",
      colorTextMuted: "#9A8F7E",
      colorTextInverse: "#0E0C09",
      fontDisplay: "Playfair Display",
      fontBody: "Cormorant Garamond",
      fontMono: "DM Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.02em",
      letterSpacingBody: "0",
      lineHeightBody: "1.7",
      borderRadius: "2px",
      borderRadiusButton: "2px",
      borderRadiusInput: "2px",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1200px",
      buttonStyle: "outline",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.4, 0, 0.2, 1)",
      hoverEffect: "underline",
      scrollAnimation: "fadeUp",
      animationStagger: "0.1s",
      backgroundTexture: "grain",
      dividerStyle: "line",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(to bottom, rgba(14,12,9,0.4), rgba(14,12,9,0.8))",
    },
  },
  {
    styleKey: "analog_warmth",
    name: "Analog Warmth",
    category: "Music",
    description: "Indie record store, warm vinyl energy. Earthy, handcrafted, nostalgic.",
    sortOrder: 1,
    tokens: {
      colorBackground: "#F5EDE0",
      colorBackgroundAlt: "#EDE0CF",
      colorSurface: "#FFF8F0",
      colorBorder: "#C9B89A",
      colorAccent: "#A0522D",
      colorAccentHover: "#8B3A1A",
      colorText: "#2D1F0E",
      colorTextMuted: "#7A6040",
      colorTextInverse: "#F5EDE0",
      fontDisplay: "Libre Baskerville",
      fontBody: "Source Serif 4",
      fontMono: "Courier Prime",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.01em",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.8",
      borderRadius: "6px",
      borderRadiusButton: "6px",
      borderRadiusInput: "6px",
      sectionPaddingY: "4rem",
      containerMaxWidth: "1100px",
      buttonStyle: "filled",
      buttonTextTransform: "none",
      buttonLetterSpacing: "0",
      buttonBorderWidth: "0",
      buttonFontFamily: "body",
      transitionSpeed: "medium",
      transitionEasing: "ease-in-out",
      hoverEffect: "lift",
      scrollAnimation: "fadeIn",
      animationStagger: "0.15s",
      backgroundTexture: "noise",
      dividerStyle: "ornament",
      cardStyle: "elevated",
      heroOverlay: "linear-gradient(to bottom, rgba(45,31,14,0.3), rgba(45,31,14,0.6))",
    },
  },
  {
    styleKey: "neon_underground",
    name: "Neon Underground",
    category: "Music",
    description: "Late night club flyer meets high-end electronic artist site. Dark, electric, unapologetic.",
    sortOrder: 2,
    tokens: {
      colorBackground: "#000000",
      colorBackgroundAlt: "#0A0A0A",
      colorSurface: "#111111",
      colorBorder: "#333333",
      colorAccent: "#00FFE0",
      colorAccentHover: "#00CCB4",
      colorText: "#FFFFFF",
      colorTextMuted: "#999999",
      colorTextInverse: "#000000",
      fontDisplay: "Space Grotesk",
      fontBody: "Inter",
      fontMono: "Space Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.05em",
      letterSpacingBody: "0",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1200px",
      buttonStyle: "filled",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.15em",
      buttonBorderWidth: "2px",
      buttonFontFamily: "display",
      transitionSpeed: "fast",
      transitionEasing: "linear",
      hoverEffect: "glow",
      scrollAnimation: "slideLeft",
      animationStagger: "0.05s",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "brutalist",
      heroOverlay: "linear-gradient(to bottom, rgba(0,255,224,0.1), rgba(0,0,0,0.9))",
    },
  },
  {
    styleKey: "golden_era",
    name: "Golden Era",
    category: "Music",
    description: "90s hip-hop luxury. Rich, confident, gold and black. Sample culture meets high fashion.",
    sortOrder: 3,
    tokens: {
      colorBackground: "#0A0A08",
      colorBackgroundAlt: "#141210",
      colorSurface: "#1C1A16",
      colorBorder: "#4A3F1A",
      colorAccent: "#D4A017",
      colorAccentHover: "#F0B820",
      colorText: "#F5F0E0",
      colorTextMuted: "#8A7A50",
      colorTextInverse: "#0A0A08",
      fontDisplay: "Bebas Neue",
      fontBody: "Outfit",
      fontMono: "Space Mono",
      fontDisplayWeight: "400",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.08em",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1200px",
      buttonStyle: "filled",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "0",
      buttonFontFamily: "display",
      transitionSpeed: "medium",
      transitionEasing: "ease-out",
      hoverEffect: "lift",
      scrollAnimation: "fadeUp",
      animationStagger: "0.1s",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "flat",
      heroOverlay: "linear-gradient(135deg, rgba(212,160,23,0.2), rgba(10,10,8,0.8))",
    },
  },
  {
    styleKey: "lofi_bedroom",
    name: "Lo-Fi Bedroom",
    category: "Music",
    description: "Cozy, intimate, DIY. Soft, warm, approachable. Like a Bandcamp page with great taste.",
    sortOrder: 4,
    tokens: {
      colorBackground: "#FBF5EE",
      colorBackgroundAlt: "#F2E8DC",
      colorSurface: "#FFFFFF",
      colorBorder: "#DDD0C0",
      colorAccent: "#C4818A",
      colorAccentHover: "#AE6A73",
      colorText: "#3D3430",
      colorTextMuted: "#9A8878",
      colorTextInverse: "#FBF5EE",
      fontDisplay: "Fraunces",
      fontBody: "Lora",
      fontMono: "DM Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.02em",
      letterSpacingBody: "0",
      lineHeightBody: "1.8",
      borderRadius: "16px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "12px",
      sectionPaddingY: "4rem",
      containerMaxWidth: "1000px",
      buttonStyle: "ghost",
      buttonTextTransform: "none",
      buttonLetterSpacing: "0",
      buttonBorderWidth: "1.5px",
      buttonFontFamily: "body",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      hoverEffect: "lift",
      scrollAnimation: "fadeIn",
      animationStagger: "0.2s",
      backgroundTexture: "none",
      dividerStyle: "none",
      cardStyle: "elevated",
      heroOverlay: "linear-gradient(to bottom, rgba(61,52,48,0.2), rgba(61,52,48,0.5))",
    },
  },
  {
    styleKey: "classical_prestige",
    name: "Classical Prestige",
    category: "Music",
    description: "Concert hall program meets modern luxury. Formal, serious, deeply typographic.",
    sortOrder: 5,
    tokens: {
      colorBackground: "#FAF8F3",
      colorBackgroundAlt: "#F0EDE4",
      colorSurface: "#FFFFFF",
      colorBorder: "#D0C8B8",
      colorAccent: "#8B1A2F",
      colorAccentHover: "#6B0F22",
      colorText: "#1A2040",
      colorTextMuted: "#7A7A8A",
      colorTextInverse: "#FAF8F3",
      fontDisplay: "EB Garamond",
      fontBody: "Crimson Pro",
      fontMono: "Courier Prime",
      fontDisplayWeight: "600",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.01em",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.9",
      borderRadius: "3px",
      borderRadiusButton: "3px",
      borderRadiusInput: "3px",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1100px",
      buttonStyle: "outline",
      buttonTextTransform: "capitalize",
      buttonLetterSpacing: "0.05em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "ease-in-out",
      hoverEffect: "none",
      scrollAnimation: "fadeIn",
      animationStagger: "0.2s",
      backgroundTexture: "none",
      dividerStyle: "ornament",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(to bottom, rgba(26,32,64,0.3), rgba(26,32,64,0.6))",
    },
  },
  {
    styleKey: "rave_architecture",
    name: "Rave Architecture",
    category: "Music",
    description: "Industrial rave poster meets Bauhaus design. Stark, geometric, confrontational.",
    sortOrder: 6,
    tokens: {
      colorBackground: "#FFFFFF",
      colorBackgroundAlt: "#F0F0F0",
      colorSurface: "#FAFAFA",
      colorBorder: "#000000",
      colorAccent: "#FF0000",
      colorAccentHover: "#CC0000",
      colorText: "#000000",
      colorTextMuted: "#555555",
      colorTextInverse: "#FFFFFF",
      fontDisplay: "Archivo Black",
      fontBody: "Archivo",
      fontMono: "IBM Plex Mono",
      fontDisplayWeight: "900",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.01em",
      letterSpacingBody: "0",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "4rem",
      containerMaxWidth: "1200px",
      buttonStyle: "brutalist",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "3px",
      buttonFontFamily: "display",
      transitionSpeed: "fast",
      transitionEasing: "linear",
      hoverEffect: "none",
      scrollAnimation: "none",
      animationStagger: "0",
      backgroundTexture: "dots",
      dividerStyle: "line",
      cardStyle: "brutalist",
      heroOverlay: "none",
    },
  },
  {
    styleKey: "soul_gospel",
    name: "Soul & Gospel",
    category: "Music",
    description: "Warmth, spirit, depth. Rich jewel tones, celebratory but grounded.",
    sortOrder: 7,
    tokens: {
      colorBackground: "#2D1B3D",
      colorBackgroundAlt: "#3A2250",
      colorSurface: "#4A2D60",
      colorBorder: "#6B4A80",
      colorAccent: "#D4A830",
      colorAccentHover: "#F0C040",
      colorText: "#F5E8C8",
      colorTextMuted: "#C0A080",
      colorTextInverse: "#2D1B3D",
      fontDisplay: "Playfair Display",
      fontBody: "Lora",
      fontMono: "DM Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "italic",
      letterSpacingDisplay: "0",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.8",
      borderRadius: "8px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "8px",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1100px",
      buttonStyle: "filled",
      buttonTextTransform: "capitalize",
      buttonLetterSpacing: "0.05em",
      buttonBorderWidth: "0",
      buttonFontFamily: "display",
      transitionSpeed: "medium",
      transitionEasing: "ease-in-out",
      hoverEffect: "glow",
      scrollAnimation: "fadeUp",
      animationStagger: "0.15s",
      backgroundTexture: "none",
      dividerStyle: "ornament",
      cardStyle: "elevated",
      heroOverlay: "linear-gradient(to bottom, rgba(45,27,61,0.4), rgba(45,27,61,0.8))",
    },
  },
  {
    styleKey: "singer_songwriter",
    name: "Singer-Songwriter",
    category: "Music",
    description: "Road-worn and honest. Tour poster meets literary journal. Sparse, direct, real.",
    sortOrder: 8,
    tokens: {
      colorBackground: "#F0E8D0",
      colorBackgroundAlt: "#E6DCC4",
      colorSurface: "#F8F2E0",
      colorBorder: "#B8A880",
      colorAccent: "#5C7A5A",
      colorAccentHover: "#4A6248",
      colorText: "#1C1410",
      colorTextMuted: "#6A5C40",
      colorTextInverse: "#F0E8D0",
      fontDisplay: "Abril Fatface",
      fontBody: "Merriweather",
      fontMono: "Courier Prime",
      fontDisplayWeight: "400",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.01em",
      letterSpacingBody: "0",
      lineHeightBody: "1.8",
      borderRadius: "4px",
      borderRadiusButton: "4px",
      borderRadiusInput: "4px",
      sectionPaddingY: "4rem",
      containerMaxWidth: "1100px",
      buttonStyle: "outline",
      buttonTextTransform: "none",
      buttonLetterSpacing: "0.03em",
      buttonBorderWidth: "1.5px",
      buttonFontFamily: "body",
      transitionSpeed: "medium",
      transitionEasing: "ease-in-out",
      hoverEffect: "lift",
      scrollAnimation: "fadeUp",
      animationStagger: "0.1s",
      backgroundTexture: "grain",
      dividerStyle: "line",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(to bottom, rgba(28,20,16,0.2), rgba(28,20,16,0.6))",
    },
  },
  {
    styleKey: "ambient_drift",
    name: "Ambient Drift",
    category: "Music",
    description: "Meditative, expansive, otherworldly. Like staring at a slow-moving nebula.",
    sortOrder: 9,
    tokens: {
      colorBackground: "#0A0C14",
      colorBackgroundAlt: "#0F1220",
      colorSurface: "#141826",
      colorBorder: "#2A2F45",
      colorAccent: "#7B68B0",
      colorAccentHover: "#9580D0",
      colorText: "#D4CCE8",
      colorTextMuted: "#7A7890",
      colorTextInverse: "#0A0C14",
      fontDisplay: "Josefin Sans",
      fontBody: "Raleway",
      fontMono: "DM Mono",
      fontDisplayWeight: "300",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.2em",
      letterSpacingBody: "0.05em",
      lineHeightBody: "1.9",
      borderRadius: "16px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "16px",
      sectionPaddingY: "6rem",
      containerMaxWidth: "1000px",
      buttonStyle: "ghost",
      buttonTextTransform: "lowercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.23, 1, 0.32, 1)",
      hoverEffect: "glow",
      scrollAnimation: "fadeIn",
      animationStagger: "0.25s",
      backgroundTexture: "none",
      dividerStyle: "none",
      cardStyle: "elevated",
      heroOverlay: "linear-gradient(135deg, rgba(123,104,176,0.2), rgba(10,12,20,0.9))",
    },
  },
  {
    styleKey: "gallery_white",
    name: "Gallery White",
    category: "Visual Art",
    description: "Chelsea gallery opening. Pure, confident, artwork-first. Lets the work breathe.",
    sortOrder: 10,
    tokens: {
      colorBackground: "#FFFFFF",
      colorBackgroundAlt: "#F5F5F5",
      colorSurface: "#FFFFFF",
      colorBorder: "#E0E0E0",
      colorAccent: "#000000",
      colorAccentHover: "#333333",
      colorText: "#000000",
      colorTextMuted: "#777777",
      colorTextInverse: "#FFFFFF",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Cormorant",
      fontMono: "DM Mono",
      fontDisplayWeight: "600",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.02em",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.8",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "6rem",
      containerMaxWidth: "1100px",
      buttonStyle: "outline",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "ease-in-out",
      hoverEffect: "none",
      scrollAnimation: "fadeIn",
      animationStagger: "0.2s",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "flat",
      heroOverlay: "none",
    },
  },
  {
    styleKey: "studio_brutalism",
    name: "Studio Brutalism",
    category: "Visual Art",
    description: "Artist's working studio. Raw, unpolished by design, confrontational honesty.",
    sortOrder: 11,
    tokens: {
      colorBackground: "#F0EDE8",
      colorBackgroundAlt: "#E4E0D8",
      colorSurface: "#FAFAF8",
      colorBorder: "#000000",
      colorAccent: "#FF4500",
      colorAccentHover: "#CC3600",
      colorText: "#000000",
      colorTextMuted: "#444444",
      colorTextInverse: "#F0EDE8",
      fontDisplay: "Barlow Condensed",
      fontBody: "Barlow",
      fontMono: "IBM Plex Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.01em",
      letterSpacingBody: "0",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "4rem",
      containerMaxWidth: "1200px",
      buttonStyle: "brutalist",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.05em",
      buttonBorderWidth: "3px",
      buttonFontFamily: "display",
      transitionSpeed: "fast",
      transitionEasing: "linear",
      hoverEffect: "none",
      scrollAnimation: "none",
      animationStagger: "0",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "brutalist",
      heroOverlay: "none",
    },
  },
  {
    styleKey: "darkroom",
    name: "Darkroom",
    category: "Visual Art",
    description: "Photography exhibition. Dark, cinematic, image-first. Every surface frames the work.",
    sortOrder: 12,
    tokens: {
      colorBackground: "#0D0D0D",
      colorBackgroundAlt: "#141414",
      colorSurface: "#1A1A1A",
      colorBorder: "#2A2A2A",
      colorAccent: "#C0392B",
      colorAccentHover: "#E74C3C",
      colorText: "#F0F0F0",
      colorTextMuted: "#808080",
      colorTextInverse: "#0D0D0D",
      fontDisplay: "Syne",
      fontBody: "Inter",
      fontMono: "Space Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.05em",
      letterSpacingBody: "0",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1200px",
      buttonStyle: "ghost",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "medium",
      transitionEasing: "ease-out",
      hoverEffect: "none",
      scrollAnimation: "fadeIn",
      animationStagger: "0.1s",
      backgroundTexture: "grain",
      dividerStyle: "none",
      cardStyle: "flat",
      heroOverlay: "linear-gradient(to bottom, rgba(13,13,13,0.3), rgba(13,13,13,0.9))",
    },
  },
  {
    styleKey: "lit_mag",
    name: "Lit Mag",
    category: "Literary & Film",
    description: "Independent literary magazine. Serious, considered, typographically obsessed.",
    sortOrder: 13,
    tokens: {
      colorBackground: "#FAF8F5",
      colorBackgroundAlt: "#F0EDE8",
      colorSurface: "#FFFFFF",
      colorBorder: "#D8D0C8",
      colorAccent: "#8B2635",
      colorAccentHover: "#6B1A27",
      colorText: "#2D2820",
      colorTextMuted: "#7A6A5A",
      colorTextInverse: "#FAF8F5",
      fontDisplay: "Playfair Display",
      fontBody: "Lora",
      fontMono: "Courier Prime",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.9",
      borderRadius: "2px",
      borderRadiusButton: "2px",
      borderRadiusInput: "2px",
      sectionPaddingY: "4rem",
      containerMaxWidth: "900px",
      buttonStyle: "ghost",
      buttonTextTransform: "lowercase",
      buttonLetterSpacing: "0",
      buttonBorderWidth: "0",
      buttonFontFamily: "body",
      transitionSpeed: "slow",
      transitionEasing: "ease",
      hoverEffect: "underline",
      scrollAnimation: "fadeIn",
      animationStagger: "0.15s",
      backgroundTexture: "none",
      dividerStyle: "ornament",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(to bottom, rgba(45,40,32,0.3), rgba(45,40,32,0.6))",
    },
  },
  {
    styleKey: "midnight_cinema",
    name: "Midnight Cinema",
    category: "Literary & Film",
    description: "Arthouse film poster meets director's personal site. Dark, cinematic, dramatic.",
    sortOrder: 14,
    tokens: {
      colorBackground: "#050508",
      colorBackgroundAlt: "#0D0D12",
      colorSurface: "#141418",
      colorBorder: "#2A2A35",
      colorAccent: "#8B0000",
      colorAccentHover: "#AA0000",
      colorText: "#E8E4DC",
      colorTextMuted: "#888880",
      colorTextInverse: "#050508",
      fontDisplay: "Bebas Neue",
      fontBody: "Libre Baskerville",
      fontMono: "Courier Prime",
      fontDisplayWeight: "400",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.1em",
      letterSpacingBody: "0",
      lineHeightBody: "1.7",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1100px",
      buttonStyle: "filled",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.1em",
      buttonBorderWidth: "0",
      buttonFontFamily: "display",
      transitionSpeed: "medium",
      transitionEasing: "ease-out",
      hoverEffect: "lift",
      scrollAnimation: "slideLeft",
      animationStagger: "0.1s",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(to bottom, rgba(5,5,8,0.5), rgba(5,5,8,0.9))",
    },
  },
  {
    styleKey: "luxury_minimal",
    name: "Luxury Minimal",
    category: "Universal",
    description: "Fashion house meets creative agency. Effortless wealth. Nothing unnecessary.",
    sortOrder: 15,
    tokens: {
      colorBackground: "#FAF9F7",
      colorBackgroundAlt: "#F0EDE8",
      colorSurface: "#FFFFFF",
      colorBorder: "#E0D8CE",
      colorAccent: "#C8A882",
      colorAccentHover: "#B09060",
      colorText: "#1A1A1A",
      colorTextMuted: "#888880",
      colorTextInverse: "#FAF9F7",
      fontDisplay: "Cormorant Garamond",
      fontBody: "Raleway",
      fontMono: "DM Mono",
      fontDisplayWeight: "600",
      fontBodyWeight: "300",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.05em",
      letterSpacingBody: "0.08em",
      lineHeightBody: "1.9",
      borderRadius: "2px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "4px",
      sectionPaddingY: "6rem",
      containerMaxWidth: "1100px",
      buttonStyle: "outline",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.15em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.4, 0, 0.2, 1)",
      hoverEffect: "glow",
      scrollAnimation: "fadeIn",
      animationStagger: "0.2s",
      backgroundTexture: "none",
      dividerStyle: "line",
      cardStyle: "flat",
      heroOverlay: "linear-gradient(to bottom, rgba(26,26,26,0.2), rgba(26,26,26,0.5))",
    },
  },
  {
    styleKey: "zine_energy",
    name: "Zine Energy",
    category: "Universal",
    description: "Cut-and-paste zine energy with digital polish. Irreverent, layered, anti-corporate.",
    sortOrder: 16,
    tokens: {
      colorBackground: "#F5F5F0",
      colorBackgroundAlt: "#EBEBE4",
      colorSurface: "#FFFFFF",
      colorBorder: "#000000",
      colorAccent: "#FFE600",
      colorAccentHover: "#CCBB00",
      colorText: "#000000",
      colorTextMuted: "#555555",
      colorTextInverse: "#000000",
      fontDisplay: "Oswald",
      fontBody: "Source Sans 3",
      fontMono: "Courier Prime",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.02em",
      letterSpacingBody: "0",
      lineHeightBody: "1.6",
      borderRadius: "0",
      borderRadiusButton: "0",
      borderRadiusInput: "0",
      sectionPaddingY: "3rem",
      containerMaxWidth: "1200px",
      buttonStyle: "brutalist",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.05em",
      buttonBorderWidth: "3px",
      buttonFontFamily: "display",
      transitionSpeed: "fast",
      transitionEasing: "linear",
      hoverEffect: "none",
      scrollAnimation: "none",
      animationStagger: "0",
      backgroundTexture: "dots",
      dividerStyle: "line",
      cardStyle: "brutalist",
      heroOverlay: "none",
    },
  },
  {
    styleKey: "coastal_studio",
    name: "Coastal Studio",
    category: "Universal",
    description: "Creative wellness. Open, airy, natural light. Calm the moment you land on it.",
    sortOrder: 17,
    tokens: {
      colorBackground: "#F5F0E8",
      colorBackgroundAlt: "#EDE8DC",
      colorSurface: "#FFFFFF",
      colorBorder: "#D8D0C4",
      colorAccent: "#7A9E8A",
      colorAccentHover: "#5E8470",
      colorText: "#4A4238",
      colorTextMuted: "#9A8E80",
      colorTextInverse: "#F5F0E8",
      fontDisplay: "Fraunces",
      fontBody: "Lora",
      fontMono: "DM Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "-0.01em",
      letterSpacingBody: "0",
      lineHeightBody: "1.8",
      borderRadius: "12px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "12px",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1100px",
      buttonStyle: "filled",
      buttonTextTransform: "none",
      buttonLetterSpacing: "0",
      buttonBorderWidth: "0",
      buttonFontFamily: "body",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.25, 0.46, 0.45, 0.94)",
      hoverEffect: "lift",
      scrollAnimation: "fadeUp",
      animationStagger: "0.2s",
      backgroundTexture: "none",
      dividerStyle: "none",
      cardStyle: "elevated",
      heroOverlay: "linear-gradient(to bottom, rgba(74,66,56,0.2), rgba(74,66,56,0.5))",
    },
  },
  {
    styleKey: "maximalist_baroque",
    name: "Maximalist Baroque",
    category: "Universal",
    description: "Too much is never enough. Rich, layered, ornate. For artists who make a statement.",
    sortOrder: 18,
    tokens: {
      colorBackground: "#0D2B1A",
      colorBackgroundAlt: "#1A3D28",
      colorSurface: "#1A3D28",
      colorBorder: "#B8860B",
      colorAccent: "#FFD700",
      colorAccentHover: "#FFC400",
      colorText: "#F5E6C8",
      colorTextMuted: "#B8A880",
      colorTextInverse: "#0D2B1A",
      fontDisplay: "Playfair Display",
      fontBody: "Cormorant Garamond",
      fontMono: "DM Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "italic",
      letterSpacingDisplay: "0.02em",
      letterSpacingBody: "0.01em",
      lineHeightBody: "1.8",
      borderRadius: "8px",
      borderRadiusButton: "9999px",
      borderRadiusInput: "8px",
      sectionPaddingY: "6rem",
      containerMaxWidth: "1100px",
      buttonStyle: "filled",
      buttonTextTransform: "capitalize",
      buttonLetterSpacing: "0.05em",
      buttonBorderWidth: "2px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.4, 0, 0.2, 1)",
      hoverEffect: "glow",
      scrollAnimation: "fadeUp",
      animationStagger: "0.15s",
      backgroundTexture: "grain",
      dividerStyle: "ornament",
      cardStyle: "bordered",
      heroOverlay: "linear-gradient(135deg, rgba(255,215,0,0.2), rgba(13,43,26,0.8))",
    },
  },
  {
    styleKey: "future_primitive",
    name: "Future Primitive",
    category: "Universal",
    description: "Ancient meets alien. Ritual meets technology. For artists who don't fit a category.",
    sortOrder: 19,
    tokens: {
      colorBackground: "#0E0B07",
      colorBackgroundAlt: "#1A1510",
      colorSurface: "#1F1A12",
      colorBorder: "#3D3020",
      colorAccent: "#E86C3A",
      colorAccentHover: "#FF8050",
      colorText: "#EDE8DC",
      colorTextMuted: "#8A8070",
      colorTextInverse: "#0E0B07",
      fontDisplay: "Syne",
      fontBody: "Outfit",
      fontMono: "Space Mono",
      fontDisplayWeight: "700",
      fontBodyWeight: "400",
      fontDisplayStyle: "normal",
      letterSpacingDisplay: "0.1em",
      letterSpacingBody: "0.02em",
      lineHeightBody: "1.7",
      borderRadius: "2px",
      borderRadiusButton: "0",
      borderRadiusInput: "2px",
      sectionPaddingY: "5rem",
      containerMaxWidth: "1200px",
      buttonStyle: "ghost",
      buttonTextTransform: "uppercase",
      buttonLetterSpacing: "0.15em",
      buttonBorderWidth: "1px",
      buttonFontFamily: "display",
      transitionSpeed: "slow",
      transitionEasing: "cubic-bezier(0.23, 1, 0.32, 1)",
      hoverEffect: "glow",
      scrollAnimation: "fadeIn",
      animationStagger: "0.2s",
      backgroundTexture: "noise",
      dividerStyle: "line",
      cardStyle: "flat",
      heroOverlay: "linear-gradient(to bottom, rgba(232,108,58,0.15), rgba(14,11,7,0.9))",
    },
  },
];

export const THEMES_BY_KEY = Object.fromEntries(
  THEMES.map((t) => [t.styleKey, t])
) as Record<string, SiteStyleDefinition>;

export const DEFAULT_STYLE_KEY = "editorial_noir";
